#pragma once

#include "common/native_common.hpp"
#include "stc/stc_native.hpp"
#include "stcf_original/stcf_original_native.hpp"
#include "baf/baf_native.hpp"
#include "ebf/ebf_native.hpp"
#include "knoise/knoise_native.hpp"
#include "ynoise/ynoise_native.hpp"
#include "time_surface/time_surface_native.hpp"
#include "event_flow/event_flow_native.hpp"
#include "mlpf/mlpf_native.hpp"
#include "pfd/pfd_native.hpp"
#include "n149/n149_native.hpp"
#include "n149/n149_rtl_fixed_native.hpp"
